url: http://barnabysmithmusic.co.uk
baseurl: 

# Site settings
title: Barnaby Smith — Composer
email: barnabysmithmusic@gmail.com
description: "All about Barnaby Smith's composition work."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BarnSmithMusic
  - title: facebook
    url: https://www.facebook.com/barnabysmithmusic
  - title: soundcloud
    url: https://soundcloud.com/barnabysmithmusic
  - title: google-plus
    url: https://plus.google.com/114472466900718797549/posts
  - title: linkedin 
    url: https://uk.linkedin.com/pub/barnaby-smith/9/584/b47/
# - title: github
#   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Radway Green Business Centre
  - line: Radway Green
  - line: Crewe
  - line: Cheshire
  - line: CW2 5PR

# Build settings
markdown: kramdown
permalink: pretty